version: "3"


volumes:
  node_modules:

services:

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: digitalmarketplace
      POSTGRES_PASSWORD: digitalmarketplace
      POSTGRES_DB: digitalmarketplace

  db-test:
    image: postgres:10
    environment:
      POSTGRES_USER: digitalmarketplace
      POSTGRES_PASSWORD: digitalmarketplace
      POSTGRES_DB: dm_test

  keycloak:
    image: keycloak
    env_file:
      - .env
    build: 
      context: ./keycloak
      args:
        # Create Github application at https://github.com/settings/applications/new
        - GITHUBID=${GITHUBID}
        - GITHUBSECRET=${GITHUBSECRET}
        - KEYCLOAKURL=http://localhost:8080
        - ROOTURL=http://localhost:3000
        - KEYCLOAK_CLIENT_SECRET=3e1ac83e-553a-4811-8d5a-b0d5b8f4b332
    ports:
      - 8080:8080
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  ui:
    image: devexchange
    build: 
      context: .
      target: development
    ports:
      - 3000:3000
      - 5000:5000 # Doc
    volumes:
      - ./:/usr/app/
      - node_modules:/usr/app/node_modules
    #command: bash -c "pm2-runtime ecosystem.config.js"
    depends_on: 
      - keycloak
      - db
    env_file:
      - .env
    # La variable KEYCLOAK_URL est utilisée 
    # * coté client (qui ne reconnait pas le hostname du conteneur)
    # * coté serveur (qui ne peux pas trouver localhost:8080)
    # En utilisant le réseau host, on rend localhost:8080 accessible
    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - POSTGRESQL_SERVICE_HOST=db
      - POSTGRESQL_SERVICE_PORT=5432
      - TIMEZONE=Canada/Eastern
      - DATABASE_USERNAME=digitalmarketplace
      - DATABASE_PASSWORD=digitalmarketplace
      - DATABASE_NAME=digitalmarketplace
      - TEST_DATABASE_NAME=dm_test
      - TEST_POSTGRESQL_SERVICE_HOST=db-test
      - COOKIE_SECRET=foobar
      - ORIGIN=http://localhost:3000
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASS=admin
      - KEYCLOAK_CLIENT_ID=dm-app
      - KEYCLOAK_REALM=digitalmarketplace
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_PUBLIC_URL=http://localhost:8080
      - FILE_STORAGE_DIR=./tmp
      - SCHEDULED_DOWNTIME=
      - KNEX_DEBUG=false
      - UPDATE_HOOK_THROTTLE=60000
      - SERVICE_TOKEN_HASH=
      - SHOW_TEST_INDICATOR=true
      - SWAGGER_ENABLE=true
      - SWAGGER_UI_PATH=/swagger
      - VENDOR_ACCOUNT_CREATION_DISABLED=1
      - KEYCLOAK_CLIENT_SECRET=3e1ac83e-553a-4811-8d5a-b0d5b8f4b332
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5999:5900
    volumes:
      - /dev/shm:/dev/shm
