version: "3"
services:
  db:
    image: postgres:10
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      POSTGRES_USER: digitalmarketplace
      POSTGRES_PASSWORD: digitalmarketplace
      POSTGRES_DB: digitalmarketplace

  db-test:
    image: postgres:10
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      POSTGRES_USER: digitalmarketplace
      POSTGRES_PASSWORD: digitalmarketplace
      POSTGRES_DB: dm_test

  keycloak:
    image: keycloak
    build: 
      context: ./keycloak
      args:
        # Create Github application at https://github.com/settings/applications/new
        - GITHUBID=${GITHUBID}
        - GITHUBSECRET=${GITHUBSECRET}
        - KEYCLOAKURL=http://localhost:8080
        - ROOTURL=http://localhost:3000
    healthcheck:
      test: curl http://localhost:8080 --connect-timeout 1 --silent --stderr /dev/null > /dev/null
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      
  ui:
    image: devexchange
    build: 
      context: .
      target: development
    healthcheck:
      test: curl http://localhost:3000 --connect-timeout 1 --silent > /dev/null
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on: 
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
      db-test:
        condition: service_healthy

    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - POSTGRESQL_SERVICE_HOST=db
      - POSTGRESQL_SERVICE_PORT=5432
      - TIMEZONE=Canada/Eastern
      - DATABASE_USERNAME=digitalmarketplace
      - DATABASE_PASSWORD=digitalmarketplace
      - DATABASE_NAME=digitalmarketplace
      - TEST_DATABASE_NAME=dm_test
      - TEST_POSTGRESQL_SERVICE_HOST=db-test
      - COOKIE_SECRET=foobar
      - ORIGIN=http://localhost:3000
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASS=admin
      - KEYCLOAK_CLIENT_ID=dm-app
      - KEYCLOAK_REALM=digitalmarketplace
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_CLIENT_SECRET=random1234
      - FILE_STORAGE_DIR=./tmp
      - SCHEDULED_DOWNTIME=
      - KNEX_DEBUG=false
      - UPDATE_HOOK_THROTTLE=60000
      - SERVICE_TOKEN_HASH=
      - SHOW_TEST_INDICATOR=true
      - SWAGGER_ENABLE=true
      - SWAGGER_UI_PATH=/swagger
      - VENDOR_ACCOUNT_CREATION_DISABLED=1
      - CI=true

  selenium:
    image: selenium/standalone-chrome-debug
    healthcheck:
      test: curl http://localhost:4444 --connect-timeout 1 --silent --stderr /dev/null > /dev/null
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on: 
      ui:
        condition: service_healthy