version: "3"


volumes:
  node_modules:

services:

  db:
    image: postgres:10
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "digitalmarketplace", "-U", "digitalmarketplace" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      POSTGRES_USER: digitalmarketplace
      POSTGRES_PASSWORD: digitalmarketplace
      POSTGRES_DB: digitalmarketplace

  keycloak:
    image: keycloak
    env_file:
      - .env
    build: 
      context: ./keycloak
      args:
        # Create Github application at https://github.com/settings/applications/new
        - GITHUBID=${GITHUBID}
        - GITHUBSECRET=${GITHUBSECRET}
        - KEYCLOAKURL=http://localhost:8080
        - ROOTURL=http://localhost:4001
        - KEYCLOAK_CLIENT_SECRET=3e1ac83e-553a-4811-8d5a-b0d5b8f4b332
    healthcheck:
      test: curl http://localhost:8080 --connect-timeout 1 --silent --stderr /dev/null > /dev/null
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s
    ports:
      - 8080:8080
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  backend:
    image: devexchange.prod
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 4001:3000
    depends_on: 
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - .env
    # La variable KEYCLOAK_URL est utilisée 
    # * coté client (qui ne reconnait pas le hostname du conteneur)
    # * coté serveur (qui ne peux pas trouver localhost:8080)
    # En utilisant le réseau host, on rend localhost:8080 accessible
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - MAILER_HOST=smtp.example.com
      - MAILER_PORT=443
      - POSTGRESQL_SERVICE_HOST=db
      - POSTGRESQL_SERVICE_PORT=5432
      - TIMEZONE=Canada/Eastern
      - DATABASE_USERNAME=digitalmarketplace
      - DATABASE_PASSWORD=digitalmarketplace
      - DATABASE_NAME=digitalmarketplace
      - TEST_DATABASE_NAME=dm_test
      - TEST_POSTGRESQL_SERVICE_HOST=db-test
      - COOKIE_SECRET=foobar
      - ORIGIN=http://localhost:4000
      - BACKEND_ORIGIN=http://localhost:4000
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASS=admin
      - KEYCLOAK_CLIENT_ID=dm-app
      - KEYCLOAK_REALM=digitalmarketplace
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_PUBLIC_URL=http://localhost:8080
      - FILE_STORAGE_DIR=./tmp
      - SCHEDULED_DOWNTIME=
      - KNEX_DEBUG=false
      - UPDATE_HOOK_THROTTLE=60000
      - SERVICE_TOKEN_HASH=
      - SHOW_TEST_INDICATOR=true
      - VENDOR_ACCOUNT_CREATION_DISABLED=1
      - KEYCLOAK_CLIENT_SECRET=3e1ac83e-553a-4811-8d5a-b0d5b8f4b332

  frontend:
    image: devexchange.frontend
    build: 
      context: .
      dockerfile: Dockerfile.frontend
      args: 
        - BACKEND_URL=http://localhost:4000
        - TIMEZONE=Canada/Eastern
        - SHOW_TEST_INDICATOR=true
        - PATH_PREFIX=
    ports:
      - 4000:80
    depends_on: 
      - backend



  combined:
    image: devexchange.combined
    build: 
      context: .
      dockerfile: Dockerfile.combined
    ports:
      - 5000:3000
    depends_on: 
      - keycloak
      - db
    env_file:
      - .env
    # La variable KEYCLOAK_URL est utilisée 
    # * coté client (qui ne reconnait pas le hostname du conteneur)
    # * coté serveur (qui ne peux pas trouver localhost:8080)
    # En utilisant le réseau host, on rend localhost:8080 accessible
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - MAILER_HOST=smtp.example.com
      - MAILER_PORT=443
      - POSTGRESQL_SERVICE_HOST=db
      - POSTGRESQL_SERVICE_PORT=5432
      - TIMEZONE=Canada/Eastern
      - DATABASE_USERNAME=digitalmarketplace
      - DATABASE_PASSWORD=digitalmarketplace
      - DATABASE_NAME=digitalmarketplace
      - TEST_DATABASE_NAME=dm_test
      - TEST_POSTGRESQL_SERVICE_HOST=db-test
      - COOKIE_SECRET=foobar
      - ORIGIN=http://localhost:5000
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASS=admin
      - KEYCLOAK_CLIENT_ID=dm-app
      - KEYCLOAK_REALM=digitalmarketplace
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_PUBLIC_URL=http://localhost:8080
      - FILE_STORAGE_DIR=./tmp
      - SCHEDULED_DOWNTIME=
      - KNEX_DEBUG=false
      - UPDATE_HOOK_THROTTLE=60000
      - SERVICE_TOKEN_HASH=
      - SHOW_TEST_INDICATOR=true
      - VENDOR_ACCOUNT_CREATION_DISABLED=1
      - KEYCLOAK_CLIENT_SECRET=3e1ac83e-553a-4811-8d5a-b0d5b8f4b332
